# Generated by Django 3.2.9 on 2021-12-06 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO'), ('N', 'NIÑOS')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='subCategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
