# Generated by Django 3.2.9 on 2021-12-07 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testdb', '0003_alter_categoria_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('subCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='modelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.marca')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('num_ref', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/productos')),
                ('cateogria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.categoria')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.color')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.modelo')),
                ('subCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='talla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('num_ref_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.talla'),
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estad', models.PositiveIntegerField()),
                ('fecha', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
