# Generated by Django 3.2.9 on 2021-12-07 14:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0004_auto_20211207_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estad',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('PAGD', 'Pagado'), ('ENVI', 'Enviado'), ('RECB', 'Recibido'), ('CANC', 'Cancelado'), ('DELV', 'Devuelto')], default='PEND', max_length=4),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('NO', 'Niño'), ('NA', 'Niña')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.CreateModel(
            name='productos_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.pedido')),
                ('num_ref_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testdb.producto')),
            ],
        ),
    ]
