# Generated by Django 3.2.9 on 2022-01-31 18:47

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('fecha_union', models.DateTimeField(auto_now_add=True, verbose_name='fecha union')),
                ('ultima_conexion', models.DateTimeField(auto_now=True, verbose_name='ultima conexion')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_usuario', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superusuario', models.BooleanField(default=False)),
                ('imagen_perfil', models.ImageField(blank=True, default=account.models.get_default_imagen_perfil, max_length=255, null=True, upload_to=account.models.get_imagen_perfil_filepath)),
                ('hide_email', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
