# Generated by Django 3.2.9 on 2022-05-31 21:48

import account.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('telefono', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=60, null=True)),
                ('fechaNacimiento', models.DateField(default=datetime.date.today)),
                ('genero', models.IntegerField(choices=[(0, 'Hombre'), (1, 'Mujer')], default=0)),
                ('fecha_union', models.DateTimeField(auto_now_add=True, verbose_name='fecha union')),
                ('ultima_conexion', models.DateTimeField(auto_now=True, verbose_name='ultima conexion')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_usuario', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superusuario', models.BooleanField(default=False)),
                ('imagen_perfil', models.ImageField(blank=True, default='imagen_perfil_default.png', max_length=255, null=True, upload_to=account.models.get_imagen_perfil_filepath)),
                ('hide_email', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='metodosPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pref', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='direccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=100)),
                ('direccion2', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(max_length=60)),
                ('provincia', models.CharField(max_length=60)),
                ('localidad', models.CharField(max_length=60)),
                ('codigoPostal', models.PositiveIntegerField()),
                ('direccion_pref', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
