# Generated by Django 3.2.9 on 2022-02-17 15:57

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220203_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='imagen_perfil',
            field=models.ImageField(blank=True, default='imagen_perfil_default.png', max_length=255, null=True, upload_to=account.models.get_imagen_perfil_filepath),
        ),
    ]
