# Generated by Django 3.2.9 on 2022-05-26 10:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_imagen_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='codigoPostal',
        ),
        migrations.RemoveField(
            model_name='account',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='account',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='account',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='account',
            name='provincia',
        ),
        migrations.AddField(
            model_name='account',
            name='fechaNacimiento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='account',
            name='genero',
            field=models.IntegerField(choices=[(0, 'Hombre'), (1, 'Mujer')], default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='metodosPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('metodo_pref', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='direccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=60)),
                ('direccion', models.CharField(max_length=100)),
                ('direccion2', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(max_length=60)),
                ('provincia', models.CharField(max_length=60)),
                ('localidad', models.CharField(max_length=60)),
                ('codigoPostal', models.PositiveIntegerField()),
                ('direccion_pref', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
