# Generated by Django 3.2.9 on 2022-05-31 22:00

import diverse.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('precio', models.PositiveIntegerField(default=0)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'diverse_categoria',
            },
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('hexcolor', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'diverse_color',
            },
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'diverse_marca',
            },
        ),
        migrations.CreateModel(
            name='modelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diverse.marca')),
            ],
            options={
                'db_table': 'diverse_modelo',
            },
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('PAGD', 'Pagado'), ('ENVI', 'Enviado'), ('RECB', 'Recibido'), ('CANC', 'Cancelado'), ('DELV', 'Devuelto')], default='PEND', max_length=4)),
                ('fecha', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('num_ref', models.PositiveBigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('imagen', models.ImageField(blank=True, default='imagenes_producto/imagen_producto_default.png', max_length=255, null=True, upload_to=diverse.models.get_producto_imagenes_filepath)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diverse.categoria')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diverse.color')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diverse.marca')),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diverse.modelo')),
            ],
            options={
                'db_table': 'diverse_producto',
            },
        ),
        migrations.CreateModel(
            name='sexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('NO', 'Niño'), ('NA', 'Niña')], max_length=2)),
            ],
            options={
                'db_table': 'diverse_sexo',
            },
        ),
        migrations.CreateModel(
            name='talla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'diverse_talla',
            },
        ),
        migrations.CreateModel(
            name='subCategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='default categoria', max_length=40)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='diverse.categoria')),
            ],
            options={
                'db_table': 'diverse_subcategoria',
            },
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('num_ref_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diverse.producto')),
            ],
        ),
        migrations.CreateModel(
            name='productos_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diverse.pedido')),
                ('num_ref_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diverse.producto')),
            ],
        ),
        migrations.CreateModel(
            name='productoCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrecio', models.PositiveIntegerField(default=0)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diverse.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diverse.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diverse.sexo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='subCategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diverse.subcategoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diverse.talla'),
        ),
        migrations.CreateModel(
            name='imagenesProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=diverse.models.get_more_product_images_filepath)),
                ('producto_numref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='diverse.producto')),
            ],
        ),
    ]
