# Generated by Django 3.2.9 on 2022-01-25 20:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('NO', 'Niño'), ('NA', 'Niña')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='modelo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diverse.marca')),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('PAGD', 'Pagado'), ('ENVI', 'Enviado'), ('RECB', 'Recibido'), ('CANC', 'Cancelado'), ('DELV', 'Devuelto')], default='PEND', max_length=4)),
                ('fecha', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('num_ref', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/productos')),
                ('cateogria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diverse.categoria')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diverse.color')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diverse.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diverse.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='talla',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='subCategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diverse.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('num_ref_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diverse.producto')),
            ],
        ),
        migrations.CreateModel(
            name='productos_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diverse.pedido')),
                ('num_ref_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diverse.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='subCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diverse.subcategoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diverse.talla'),
        ),
        migrations.AddField(
            model_name='marca',
            name='subCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diverse.subcategoria'),
        ),
    ]
