# Generated by Django 3.2.9 on 2022-02-08 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diverse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('NO', 'Niño'), ('NA', 'Niña')], max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cateogria',
        ),
        migrations.AddField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='diverse.categoria'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='nombre',
            field=models.CharField(default='default categoria', max_length=40),
        ),
        migrations.AddField(
            model_name='categoria',
            name='sexo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diverse.sexo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='sexo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diverse.sexo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='sexo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diverse.sexo'),
            preserve_default=False,
        ),
    ]
