# Generated by Django 3.2.9 on 2022-02-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diverse', '0002_auto_20220208_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoria',
            name='sexo',
        ),
    ]
