# Generated by Django 3.2.9 on 2022-04-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diverse', '0003_remove_subcategoria_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='subCategoria',
        ),
    ]
