# Generated by Django 3.2.9 on 2022-04-27 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diverse', '0004_auto_20220406_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diverse.categoria'),
            preserve_default=False,
        ),
    ]
