# Generated by Django 3.2.9 on 2022-05-26 10:07

import diverse.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diverse', '0005_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diverse.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diverse.color'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='imagenes_producto/imagen_producto_default.png', max_length=255, null=True, upload_to=diverse.models.get_producto_imagenes_filepath),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diverse.marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diverse.modelo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='num_ref',
            field=models.PositiveBigIntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diverse.sexo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='subCategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diverse.subcategoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diverse.talla'),
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='diverse_categoria',
        ),
        migrations.AlterModelTable(
            name='color',
            table='diverse_color',
        ),
        migrations.AlterModelTable(
            name='marca',
            table='diverse_marca',
        ),
        migrations.AlterModelTable(
            name='modelo',
            table='diverse_modelo',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='diverse_producto',
        ),
        migrations.AlterModelTable(
            name='sexo',
            table='diverse_sexo',
        ),
        migrations.AlterModelTable(
            name='subcategoria',
            table='diverse_subcategoria',
        ),
        migrations.AlterModelTable(
            name='talla',
            table='diverse_talla',
        ),
    ]
