# Generated by Django 3.2.9 on 2022-05-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diverse', '0006_auto_20220526_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hexcolor',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
