# Generated by Django 3.2.9 on 2022-05-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diverse', '0008_alter_color_hexcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hexcolor',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
