# Generated by Django 3.2.9 on 2022-05-26 12:34

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diverse', '0009_alter_color_hexcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hexcolor',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black')]),
        ),
    ]
