# Generated by Django 3.2.9 on 2022-05-29 09:32

import diverse.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diverse', '0011_alter_color_hexcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=diverse.models.get_more_product_images_filepath)),
                ('producto_numref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='diverse.producto')),
            ],
        ),
    ]
