# Generated by Django 3.2.9 on 2022-05-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diverse', '0012_imagenproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hexcolor',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
