# Generated by Django 3.2.9 on 2022-05-31 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diverse', '0013_alter_color_hexcolor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imagenproducto',
            table='diverse_imagenproducto',
        ),
    ]
