# Generated by Django 3.2.9 on 2022-06-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diverse', '0014_auto_20220601_2108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='imagenesProductos',
            new_name='imagenProducto',
        ),
        migrations.AddField(
            model_name='productocarrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
