# Generated by Django 3.2.9 on 2022-06-01 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diverse', '0015_auto_20220601_2108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='imagenesProductos',
            new_name='imagenProducto',
        ),
    ]
