# Generated by Django 3.2.9 on 2022-06-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diverse', '0015_auto_20220601_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocarrito',
            name='precio',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
