# Generated by Django 3.2.9 on 2022-06-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diverse', '0019_alter_carrito_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='estado',
            field=models.PositiveIntegerField(choices=[(0, 'En proceso'), (1, 'Completo')], default=0),
        ),
    ]
