# Generated by Django 3.2.9 on 2022-06-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diverse', '0020_alter_carrito_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='gastosEnvio',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='carrito',
            name='precioTotal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
