# Generated by Django 3.2.9 on 2022-06-02 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diverse', '0016_rename_imagenesproductos_imagenproducto'),
        ('diverse', '0021_auto_20220602_2121'),
    ]

    operations = [
    ]
